name: flutter_naver_map
description: flutter naver map plugin support android and iOS. naver map service is limited to south korea which has high accuracy.
version: 0.0.1
repository: https://github.com/SuhwanCha/flutter_naver_map

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  permission_handler: ^10.2.0
  very_good_analysis: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: map.naver.plugin.net.lbstech.naver_map_plugin
        pluginClass: NaverMapPlugin
      ios:
        pluginClass: FlutterNaverMap
