name: flutter_naver_map
description: flutter naver map plugin support android and iOS. naver map service is limited to south korea which has high accuracy.
version: 1.0.0
repository: https://github.com/SuhwanCha/flutter_naver_map

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  json_annotation: ^4.7.0
  permission_handler: ^10.2.0
  very_good_analysis: ^3.1.0

dev_dependencies:
  build_runner: ^2.3.2
  flutter_test:
    sdk: flutter
  json_serializable: ^6.5.4
flutter:
  plugin:
    platforms:
      android:
        package: map.naver.plugin.net.lbstech.naver_map_plugin
        pluginClass: NaverMapPlugin
      ios:
        pluginClass: FlutterNaverMap
